#ifndef MATHFUNCTIONS2_GLOBAL_H
#define MATHFUNCTIONS2_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MATHFUNCTIONS2_LIBRARY)
#  define MATHFUNCTIONS2SHARED_EXPORT Q_DECL_EXPORT
#else
#  define MATHFUNCTIONS2SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MATHFUNCTIONS2_GLOBAL_H
